import DS from 'ember-data';

export default DS.Model.extend({
  block_id: DS.attr(),
  company_id: DS.attr(),
  block: DS.attr(),
  block_content_entry: DS.attr(),
  title: DS.attr(),
  subtitle: DS.attr(),
  text: DS.attr(),
  text_color: DS.attr(),
  background_image: DS.attr(),
  overlay: DS.attr(),
  height: DS.attr(),
  background_color: DS.attr(),
  foreground_image: DS.attr(),
  image: DS.attr(),
  icon: DS.attr(),
  video: DS.attr(),
  primary_color: DS.attr(),
  secondary_color: DS.attr(),
  tertiary_color: DS.attr(),
  primary_cta_text: DS.attr(),
  secondary_cta_text: DS.attr(),
  primary_cta_link: DS.attr(),
  secondary_cta_link: DS.attr(),
  location: DS.attr(),
  country: DS.attr(),
  address: DS.attr(),
  city: DS.attr(),
  state: DS.attr(),
  post_code: DS.attr(),
  social_type: DS.attr(),
  social_link: DS.attr(),
  job_type_filter: DS.attr(),
  job_location_filter: DS.attr(),
  pagination: DS.attr(),
  margin_top: DS.attr(),
  margin_right: DS.attr(),
  margin_bottom: DS.attr(),
  margin_left: DS.attr(),
  padding_top: DS.attr(),
  padding_right: DS.attr(),
  padding_bottom: DS.attr(),
  padding_left: DS.attr(),
  order: DS.attr(),
});
