import DS from 'ember-data';

export default DS.Model.extend({
  //company: DS.belongsTo('company'),
  title: DS.attr("string"),
  slug: DS.attr("string"),
  description: DS.attr("string"),
  contract: DS.attr("string"),
  level: DS.attr("string"),
  city: DS.attr("string"),
  country: DS.attr("string"),
  postal_code: DS.attr("string"),
  state: DS.attr("string"),
  content: DS.attr(),
  company: DS.attr(),
  type: DS.attr(),
  questions: DS.attr(),
  location: DS.attr(),
  salary_from: DS.attr("number"),
  salary_to: DS.attr("number"),
  salary_type: DS.attr("string"),
  salary_disclosed: DS.attr(),
  status: DS.attr("string"),
  views: DS.attr("number"),
  impressions: DS.attr("number"),
  applications: DS.attr("number"),
  published_at: DS.attr("date"),
  updated_at: DS.attr("date"),
  created_at: DS.attr("date"),
  has_applied: DS.attr(),
  skills: DS.attr(),
  redirect: DS.attr("string"),
  application_status: DS.attr(),
  application_answers: DS.attr(),
  application_id: DS.attr(),
  is_recruiter: DS.attr(),
});
